service: testProject
# include extra setting
custom: ${file(./custom.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512 # optional, default is 1024. you can setting individual function.

# you can overwrite defaults here
  stage: ${opt:stage} # production stage is [prod]
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-*"
  # environmentの値は、lambda function内で
  # process.env.{key}でアクセスする
  environment:
    stage: ${self:provider.stage}
    bookTable: ${self:provider.stage}-books
    slack_webhook_url: ${self:custom.slack_webhook_url}
    slash_command_token: ${self:custom.slash_command_token}

functions:
#  hello:
#    handler: handler.hello
  book:
    handler: src/dispatcher/book.book
    events:
      - http:
          path: book
          method: post
          cors: true

resources:
  Resources:
    BookDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.bookTable}